### GET request to ResponseTransformerExtensionNoDependenciesJava
GET http://localhost:8080/ResponseTransformerExtensionNoDependenciesJava

### GET request to ResponseTransformerExtensionNoDependenciesKotlin
GET http://localhost:8080/ResponseTransformerExtensionNoDependenciesKotlin

### GET request to ResponseTransformerExtensionWithDependenciesKotlin
GET http://localhost:8080/ResponseTransformerExtensionWithDependenciesKotlin

### GET request to NoExtension
GET http://localhost:8080/noExtension