source-files-location: examples/example

source-files:
  - ResponseTransformerExtensionNoDependenciesJava.java
  - ResponseTransformerExtensionNoDependenciesKotlin.kt
  - ResponseTransformerExtensionWithDependenciesKotlin.kt

dependencies:
  - org.apache.commons:commons-lang3:3.18.0

jar-run-config:
  docker-port: 8080
  docker-container-name: wiremock-docker-easy-extensions