source-files-location: ""

source-files:
  - examples.example.ResponseTransformerExtensionNoDependenciesJava.java
  - examples.example.ResponseTransformerExtensionNoDependenciesKotlin.kt
  - examples.example.ResponseTransformerExtensionWithDependenciesKotlin.kt

dependencies:
  - org.apache.commons:commons-lang3:3.18.0

jar-run-config:
  docker-port: 8080
  docker-container-name: wiremock-docker-easy-extensions