source-files-location: extensions

source-files:
  - wdee.examples.ResponseTransformerExtensionNoDependenciesJava.java
  - wdee.examples.ResponseTransformerExtensionNoDependenciesKotlin.kt
  - wdee.examples.ResponseTransformerExtensionWithDependenciesKotlin.kt

dependencies:
  - org.apache.commons:commons-lang3:3.18.0

jar-run-config:
  docker-port: 8080
  docker-container-name: wiremock-docker-easy-extensions
  wiremock-cl-options:
    - --verbose